### PR TITLE
[Doc] Fix typo

### PR DESCRIPTION
**Pull request by zachpoblete**
I know you said you currently aren't accepting pull requests, but this is such a trivial typo fix that it would be faster for you to just
- pull this request

than
- for me to create an issue,
- then you manually make the changes.

### CODE REVIEW

**Comment by zero-plusplus** [comment]
Thanks for the report.

I can't fix it right away as I am devoting my time to developing another project.

However, I will definitely fix it, although it will take some time.

**Comment by zachpoblete** [comment]
So that's what happens when I delete my fork but the PR is still open lol. Well, probably wasn't going to get merged anyway.

**Comment by zero-plusplus** [comment]
I apologise for putting this issue on the back burner and forgetting the details of that issue.
I should have informed you that my delay in planning has delayed the correction of this problem.

---

Just recently, when I prototyped the next version of the project, I had appropriated a previous script and I have fixed that part of the problem in the above commit.

Note that this prototype has a bug, the cause of which is unknown, in that it does not accept commands until it is suddenly rebooted, and is not yet ready for release.

To be honest, my ability to manage multiple extensions at the same time is difficult and it will often take a long time to fix things.

I am currently rewriting the code from scratch for a major update of vscode-autohotkey-debug, which is expected to take quite some time.

**Comment by zachpoblete** [comment]
It's fine! It was just a very minor typo.

**Pull request closed without merging**
